# Generated by Django 3.1.4 on 2020-12-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.URLField(verbose_name='Обложка альбома'),
        ),
    ]
