# Generated by Django 3.1.4 on 2020-12-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201220_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='play_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность песни'),
        ),
    ]
