# Generated by Django 3.1.4 on 2021-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_stages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stages',
            old_name='test',
            new_name='band_mtm',
        ),
        migrations.AddField(
            model_name='band',
            name='stage_mtm',
            field=models.ManyToManyField(to='music.Stages'),
        ),
    ]
