# Generated by Django 3.1.4 on 2021-01-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210118_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='stage_mtm',
        ),
    ]
